/**
 * master-data.js
 * file:// 直開きでも動くよう、商品マスタを JS にも同梱しておく。
 * 通常は data/products.json を fetch するが、CORS で失敗した場合はこちらを使う。
 * data/products.json と内容を同期させること。
 */
window.__MASTER_FALLBACK__ = {
    products: [
        { code: "1",   name: "ボールペン 黒 0.5mm" },
        { code: "2",   name: "ボールペン 赤 0.5mm" },
        { code: "3",   name: "ボールペン 青 0.5mm" },
        { code: "4",   name: "シャープペンシル 0.5mm" },
        { code: "5",   name: "シャープペンシル 0.7mm" },
        { code: "6",   name: "鉛筆 HB" },
        { code: "7",   name: "鉛筆 2B" },
        { code: "8",   name: "消しゴム 標準" },
        { code: "9",   name: "消しゴム 大判" },
        { code: "10",  name: "修正テープ 5mm" },
        { code: "11",  name: "修正液 ボトル型" },
        { code: "12",  name: "蛍光ペン 黄" },
        { code: "13",  name: "蛍光ペン ピンク" },
        { code: "14",  name: "蛍光ペン グリーン" },
        { code: "15",  name: "蛍光ペン オレンジ" },
        { code: "16",  name: "マーカー 黒 細字" },
        { code: "17",  name: "マーカー 黒 太字" },
        { code: "18",  name: "サインペン 黒" },
        { code: "19",  name: "ホワイトボードマーカー 黒" },
        { code: "20",  name: "ホワイトボードマーカー 赤" },
        { code: "21",  name: "ホワイトボードマーカー 青" },
        { code: "22",  name: "A4ノート 横罫" },
        { code: "23",  name: "A4ノート 方眼" },
        { code: "24",  name: "A4ノート 無地" },
        { code: "25",  name: "A5ノート 横罫" },
        { code: "26",  name: "B5ノート 横罫" },
        { code: "27",  name: "メモ帳 A7" },
        { code: "28",  name: "付箋 75x75 黄" },
        { code: "29",  name: "付箋 75x25 マルチカラー" },
        { code: "30",  name: "リングノート A5" },
        { code: "31",  name: "コピー用紙 A4" },
        { code: "32",  name: "コピー用紙 A3" },
        { code: "33",  name: "コピー用紙 B5" },
        { code: "34",  name: "色画用紙 アソート" },
        { code: "35",  name: "ファイル A4 クリア" },
        { code: "36",  name: "ファイル A4 2穴" },
        { code: "37",  name: "ファイル A4 4穴" },
        { code: "38",  name: "クリアポケット A4" },
        { code: "39",  name: "封筒 長3 白" },
        { code: "40",  name: "封筒 角2 茶" },
        { code: "41",  name: "封筒 洋形 白" },
        { code: "42",  name: "クリップ 小" },
        { code: "43",  name: "クリップ 大" },
        { code: "44",  name: "ダブルクリップ 黒" },
        { code: "45",  name: "ホチキス 標準" },
        { code: "46",  name: "ホチキス針 10号" },
        { code: "47",  name: "ホチキス針 3号" },
        { code: "48",  name: "ホチキスリムーバー" },
        { code: "49",  name: "穴あけパンチ 2穴" },
        { code: "50",  name: "穴あけパンチ 強力" },
        { code: "51",  name: "セロハンテープ 18mm" },
        { code: "52",  name: "両面テープ 15mm" },
        { code: "53",  name: "ガムテープ 茶" },
        { code: "54",  name: "ガムテープ 透明" },
        { code: "55",  name: "マスキングテープ 白" },
        { code: "56",  name: "養生テープ 緑" },
        { code: "57",  name: "テープカッター 卓上" },
        { code: "58",  name: "のり スティック" },
        { code: "59",  name: "のり 液体" },
        { code: "60",  name: "瞬間接着剤" },
        { code: "61",  name: "ハサミ 標準" },
        { code: "62",  name: "ハサミ 工作用" },
        { code: "63",  name: "カッターナイフ 小" },
        { code: "64",  name: "カッターナイフ 大" },
        { code: "65",  name: "カッター替刃 小" },
        { code: "66",  name: "カッター替刃 大" },
        { code: "67",  name: "カッターマット A3" },
        { code: "68",  name: "定規 15cm" },
        { code: "69",  name: "定規 30cm" },
        { code: "70",  name: "三角定規セット" },
        { code: "71",  name: "分度器" },
        { code: "72",  name: "コンパス" },
        { code: "73",  name: "電卓 12桁" },
        { code: "74",  name: "電卓 8桁" },
        { code: "75",  name: "ペン立て" },
        { code: "76",  name: "卓上カレンダー" },
        { code: "77",  name: "壁掛けカレンダー" },
        { code: "78",  name: "スタンプ台 黒" },
        { code: "79",  name: "スタンプ台 赤" },
        { code: "80",  name: "印鑑マット" },
        { code: "81",  name: "ネームスタンプ" },
        { code: "82",  name: "領収書 ボックス" },
        { code: "83",  name: "請求書 用紙" },
        { code: "84",  name: "見積書 用紙" },
        { code: "85",  name: "伝票 3枚複写" },
        { code: "86",  name: "ラベルシール A4" },
        { code: "87",  name: "宛名シール" },
        { code: "88",  name: "バインダー A4" },
        { code: "89",  name: "クリップボード A4" },
        { code: "90",  name: "ブックエンド" },
        { code: "91",  name: "デスクトレイ" },
        { code: "92",  name: "ティッシュ ボックス" },
        { code: "93",  name: "ウェットティッシュ" },
        { code: "94",  name: "アルコール除菌" },
        { code: "95",  name: "ゴミ袋 45L" },
        { code: "96",  name: "電池 単3 4本パック" },
        { code: "97",  name: "電池 単4 4本パック" },
        { code: "98",  name: "USBメモリ 16GB" },
        { code: "99",  name: "USBケーブル Type-C" },
        { code: "100", name: "延長コード 3口" }
    ]
};
